version: '3'
services:
  server:
    build: ./server
    command: sh -c "npm install && npm dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /root/server