version: '3'
services:
  server:
    build: ./server
    container_name: server
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
  client:
    build: ./client
    container_name: client
    ports:
      - '3001:3001'
    links:
      - server
    volumes:
      - ./client:/app
